In [ ]:
# https://stackoverflow.com/questions/3241929/python-find-dominant-most-common-color-in-an-image


In [82]:
import struct
from PIL import Image
import numpy as np
import scipy
import scipy.misc
import scipy.cluster

NUM_CLUSTERS = 10

print 'reading image'
im = Image.open('shoes.jpg')
im = im.resize((150, 150))      # optional, to reduce time
ar = np.asarray(im)
shape = ar.shape
ar = ar.reshape(scipy.product(shape[:2]), shape[2]).astype(float)

print 'finding clusters'
codes, dist = scipy.cluster.vq.kmeans(ar, NUM_CLUSTERS)
print 'cluster centres:\n', codes

vecs, dist = scipy.cluster.vq.vq(ar, codes)         # assign codes
counts, bins = scipy.histogram(vecs, len(codes))    # count occurrences

index_max = scipy.argmax(counts)                    # find most frequent
peak = codes[index_max]
colour = ''.join(chr(int(c)) for c in peak).encode('hex')

reading image
finding clusters
cluster centres:
[[ 35.05583127  48.89081886 106.92493797]
 [200.86398334 144.92054129 136.31505899]
 [134.89621087  79.24162548  68.70345964]
 [173.5690004  114.62120599 104.20760826]
 [235.09889395 198.67859466 197.8415745 ]
 [ 87.26611227 119.78863479 174.93555094]
 [237.89041704 227.67790594 227.65350488]
 [ 53.45360825  83.42019197 147.35193743]
 [220.82561218 172.83454666 168.76273991]
 [ 83.9765343   35.2400722   26.46750903]]


In [84]:
colors = {}
sorted_order = np.argsort(counts)[::-1]
for i in range(len(sorted_order)):
    elem_num = sorted_order[i]
    peak = codes[elem_num]
    colour = ''.join(chr(int(c)) for c in peak).encode('hex')
    colors[i] = {colour:counts[elem_num]}

In [85]:
colors

{0: {'ebc6c5': 3079},
 1: {'dcaca8': 3037},
 2: {'c89088': 2878},
 3: {'355393': 2818},
 4: {'ad7268': 2456},
 5: {'ede3e3': 2274},
 6: {'864f44': 1803},
 7: {'23306a': 1614},
 8: {'5777ae': 1435},
 9: {'53231a': 1106}}